# File with my exceptions

RECEIVING_ERROR = 1
OK = 0


class ReceivingError(Exception):
    pass
